# Generated by Django 2.2.6 on 2020-10-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='package_type',
        ),
    ]
