# Generated by Django 2.2.6 on 2020-10-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0001_initial'),
        ('carts', '0002_auto_20201003_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotas.Quota'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_item_type',
            field=models.CharField(choices=[('PR', 'Product'), ('SE', 'Service'), ('QU', 'Quota'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
