# Generated by Django 2.2.6 on 2020-10-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201004_0918'),
        ('carts', '0003_auto_20201004_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_search_criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductSearchCriteria'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_item_type',
            field=models.CharField(choices=[('PS', 'Product Search Criteria'), ('PR', 'Product'), ('SE', 'Service'), ('QU', 'Quota'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
