# Generated by Django 2.2.6 on 2020-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20201004_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_form_type',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='image_version_id',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
