# Generated by Django 2.2.6 on 2020-10-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20201006_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='year1',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='year2',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
