# Generated by Django 2.2.6 on 2020-10-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20201013_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image_form_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='image_version_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
