# Generated by Django 2.2.6 on 2020-10-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20201014_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='output_document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
