# Generated by Django 2.2.6 on 2020-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20201022_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='year1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='year2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
