# Generated by Django 2.2.6 on 2020-10-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201003_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='entities_type',
            field=models.CharField(choices=[('RB', 'Registration of Business'), ('RC', 'Registration of Company'), ('NA', 'Not Available')], default='PD', max_length=2),
        ),
        migrations.AddField(
            model_name='service',
            name='product_type',
            field=models.CharField(choices=[('BO', 'Both'), ('PR', 'Product'), ('LS', 'Listing'), ('NA', 'Not Available')], default='PD', max_length=2),
        ),
    ]
