# Generated by Django 2.2.6 on 2020-10-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201003_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='service',
            name='address2',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address3',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='entities_type',
            field=models.CharField(choices=[('RB', 'Registration of Business'), ('RC', 'Registration of Company'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='product_type',
            field=models.CharField(choices=[('BO', 'Both'), ('PR', 'Product'), ('LS', 'Listing'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CB', 'CBID'), ('IN', 'Investigation'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
