# Generated by Django 2.2.6 on 2020-10-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20201003_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='city',
        ),
        migrations.RemoveField(
            model_name='service',
            name='country',
        ),
        migrations.RemoveField(
            model_name='service',
            name='postcode',
        ),
    ]
