# Generated by Django 2.2.6 on 2020-10-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201003_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
