# Generated by Django 2.2.6 on 2020-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20201003_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='paid',
        ),
        migrations.AlterField(
            model_name='service',
            name='product_type',
            field=models.CharField(choices=[('PR', 'Product'), ('LS', 'Listing'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
