# Generated by Django 2.2.6 on 2020-10-03 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='service',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='remarks',
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, null=True)),
                ('organisation', models.CharField(max_length=512, null=True)),
                ('address', models.CharField(max_length=512, null=True)),
                ('email_address', models.CharField(max_length=512, null=True)),
                ('phone_number', models.CharField(max_length=512, null=True)),
                ('remarks', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
    ]
