# Generated by Django 2.2.6 on 2020-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20201003_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
