# Generated by Django 2.2.6 on 2020-10-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_documentitemrequest_documentrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentItemRequest',
            new_name='DocumentRequestItem',
        ),
    ]
