# Generated by Django 2.2.6 on 2020-10-08 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0015_auto_20201006_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgovernmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('egov_request', models.CharField(choices=[('NA', 'NA'), ('AP', 'Approved'), ('PD', 'Pending')], default='NA', max_length=2)),
                ('egov_package', models.IntegerField(default=0)),
                ('egov_quota', models.IntegerField(default=0, null=True)),
                ('position_or_grade', models.CharField(blank=True, max_length=30, null=True)),
                ('head_of_department_name', models.CharField(blank=True, max_length=50, null=True)),
                ('head_of_department_position', models.CharField(blank=True, max_length=50, null=True)),
                ('head_of_department_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ministry_name', models.CharField(blank=True, max_length=50, null=True)),
                ('division_name', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
