# Generated by Django 2.2.6 on 2020-10-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20201012_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
