# Generated by Django 2.2.6 on 2020-10-12 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0018_auto_20201012_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='in_progress_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pending_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_pic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='receipt_number',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reference_id',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
