# Generated by Django 2.2.6 on 2020-10-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20201012_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='pending_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
    ]
