# Generated by Django 2.2.6 on 2020-10-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20201012_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
