# Generated by Django 2.2.6 on 2020-10-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequestitem',
            name='document_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_request_item', to='services.DocumentRequest'),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='division_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='head_of_department_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='head_of_department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='head_of_department_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='ministry_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='position_or_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
