# Generated by Django 2.2.6 on 2020-10-16 22:40

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20201016_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrequest',
            old_name='remarks',
            new_name='offence',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='court_case_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='ip_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='offical_letter_request',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('document-request-official-letter-request')),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='official_letter_egov',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('document-request-official-letter-egov')),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='reference_letter_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
