# Generated by Django 2.2.6 on 2020-10-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_egovernmentdepartment_egovernmentministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='egovernmentdepartment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
