# Generated by Django 2.2.6 on 2020-10-20 20:59

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_egovernmentdepartment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egovernmentrequest',
            name='agency_name',
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='address_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='attachment_letter',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('egovernment-request-attachment-letter')),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='egov_request',
            field=models.CharField(choices=[('NA', 'NA'), ('AP', 'Approved'), ('PD', 'Pending'), ('RJ', 'Rejected')], default='NA', max_length=2),
        ),
    ]
