# Generated by Django 2.2.6 on 2020-10-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20201020_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='egovernmentministry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='egovernmentrequest',
            name='egov_request',
            field=models.CharField(choices=[('NA', 'NA'), ('AP', 'Approved'), ('PD', 'Pending'), ('RJ', 'Rejected')], default='PD', max_length=2),
        ),
    ]
