# Generated by Django 2.2.6 on 2020-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20201020_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egovernmentrequest',
            old_name='egov_request',
            new_name='request_status',
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egovernmentrequest',
            name='request_type',
            field=models.CharField(choices=[('RG', 'Registration'), ('QU', 'Quota Request'), ('RN', 'Renew Account'), ('UI', 'Update Information')], default='RG', max_length=2),
        ),
    ]
