# Generated by Django 2.2.6 on 2020-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20201024_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='egovernmentrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
