# Generated by Django 2.2.6 on 2020-10-25 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0030_documentrequestitem_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='egovernmentrequest',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egov_request_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
