# Generated by Django 2.2.6 on 2020-10-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20201029_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequestitem',
            name='document_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approve')], default='PD', max_length=2),
        ),
    ]
