# Generated by Django 2.2.6 on 2020-10-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_documentrequestitem_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
