# Generated by Django 2.2.6 on 2020-10-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_auto_20201029_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequestitem',
            name='profile_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
