# Generated by Django 2.2.6 on 2020-10-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_documentrequestitem_profile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrequestitem',
            old_name='profile_type',
            new_name='document_name',
        ),
    ]
