# Generated by Django 2.2.6 on 2020-10-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('quotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='quota_type',
            field=models.CharField(choices=[('0A', 'Custom Listing A'), ('0B', 'Custom Listing B'), ('0C', 'Custom Listing C'), ('0D', 'Custom Listing D'), ('K1', 'KJAKP Package 1'), ('K2', 'KJAKP Package 2'), ('K3', 'KJAKP Package 3'), ('K4', 'KJAKP Package 4'), ('IM', 'Image Search')], default='EN', max_length=2),
        ),
    ]
