# Generated by Django 2.2.6 on 2020-10-18 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotas', '0002_auto_20201008_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quota',
            name='quota_type',
            field=models.CharField(choices=[('0A', 'Custom Listing A'), ('0B', 'Custom Listing B'), ('0C', 'Custom Listing C'), ('0D', 'Custom Listing D'), ('E1', 'EGov Package 1'), ('E2', 'EGov Package 2'), ('E3', 'EGov Package 3'), ('E4', 'EGov Package 4'), ('IM', 'Image Search')], default='NA', max_length=2),
        ),
    ]
