# Generated by Django 2.2.6 on 2020-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0003_auto_20201018_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='entity',
        ),
        migrations.AlterField(
            model_name='quota',
            name='quota_type',
            field=models.CharField(choices=[('0A', 'Custom Listing A'), ('0B', 'Custom Listing B'), ('0C', 'Custom Listing C'), ('0D', 'Custom Listing D'), ('E1', 'EGov Package 1'), ('E2', 'EGov Package 2'), ('E3', 'EGov Package 3'), ('E4', 'EGov Package 4'), ('DS', 'Document Search')], default='NA', max_length=2),
        ),
    ]
