# Generated by Django 2.2.6 on 2020-10-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address1',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='address2',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='address3',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organisation',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='postcode',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
