# Generated by Django 2.2.6 on 2020-10-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
