# Generated by Django 2.2.6 on 2020-10-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20201012_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('DD', 'Direct Debit'), ('WA', 'e-Wallet'), ('NA', 'Not Available')], max_length=2, null=True),
        ),
    ]
