# Generated by Django 2.2.6 on 2020-10-23 03:04

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('transaction-receipt')),
        ),
    ]
