# Generated by Django 2.2.6 on 2020-10-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_no',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
