# Generated by Django 2.2.6 on 2020-10-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20201023_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reference_id',
            new_name='reference_no',
        ),
    ]
