# Generated by Django 2.2.6 on 2020-09-30 23:17

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.TextField(default='NA')),
                ('ticket_type', models.CharField(choices=[('GN', 'General'), ('EG', 'eGovernment')], default='GN', max_length=2)),
                ('ticket_status', models.CharField(choices=[('RS', 'Resolved'), ('US', 'Unresolved')], default='US', max_length=2)),
                ('receipt_number', models.CharField(default='NA', max_length=100)),
                ('attached_document', models.FileField(null=True, upload_to=core.helpers.PathAndRename('enquiry-attached-document'))),
                ('error_screenshot', models.ImageField(null=True, upload_to=core.helpers.PathAndRename('enquiry-error-screenshot'))),
                ('error_supporting_document', models.FileField(null=True, upload_to=core.helpers.PathAndRename('enquiry-supporting-document'))),
                ('error_product', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCBID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('remarks', models.TextField(default='NA')),
                ('entity_type', models.CharField(choices=[('ROB', 'Registration of Business'), ('ROC', 'Registration of Company')], default='ROB', max_length=3)),
                ('product_type', models.CharField(choices=[('BT', 'Both'), ('LT', 'Listing'), ('PD', 'Product')], default='BT', max_length=2)),
                ('status', models.CharField(choices=[('PG', 'Pending'), ('PD', 'Paid'), ('CP', 'Completed')], default='PG', max_length=2)),
                ('pending_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_letter_number', models.CharField(default='NA', max_length=100)),
                ('ip_no', models.CharField(default='NA', max_length=100)),
                ('court_case_number', models.CharField(default='NA', max_length=100)),
                ('official_attachment', models.FileField(null=True, upload_to=core.helpers.PathAndRename('investigation-attachment-official'))),
                ('offense', models.CharField(default='NA', max_length=100)),
                ('document_request', models.FileField(null=True, upload_to=core.helpers.PathAndRename('investigation-document-request'))),
                ('submit_request', models.FileField(null=True, upload_to=core.helpers.PathAndRename('investigation-submit-request'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('subject_category', models.CharField(choices=[('GN', 'General'), ('EG', 'eGovernment')], default='GN', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('topic_category', models.CharField(choices=[('GN', 'General'), ('EG', 'eGovernment')], default='GN', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
