# Generated by Django 2.2.6 on 2020-10-08 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200930_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('ticket_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('ticket_status', models.CharField(choices=[('NA', 'Not Available')], default='PG', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryTicketSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('category', models.CharField(default='NA', max_length=100)),
                ('selection_type', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryTicketReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('receipt_number', models.CharField(default='NA', max_length=100)),
                ('message', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('enquiry_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.EnquiryTicket')),
            ],
        ),
    ]
