# Generated by Django 2.2.6 on 2020-11-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_enquiryticket_enquiryticketreply_enquiryticketselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsubject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tickettopic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
