# Generated by Django 2.2.6 on 2020-11-04 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20201104_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettopic',
            old_name='topic_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='ticketsubject',
            name='subject_category',
        ),
        migrations.AddField(
            model_name='ticketsubject',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketTopic'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
