# Generated by Django 2.2.6 on 2020-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20201104_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsubject',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
