# Generated by Django 2.2.6 on 2020-11-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_enquirynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='error_product',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='error_screenshot',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='error_supporting_document',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tel_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
