# Generated by Django 2.2.6 on 2020-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20201109_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
