# Generated by Django 2.2.6 on 2020-11-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0010_auto_20201109_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryticketreply',
            name='enquiry_ticket',
        ),
        migrations.RemoveField(
            model_name='enquiryticketreply',
            name='name',
        ),
        migrations.RemoveField(
            model_name='enquiryticketreply',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='enquiryticketreply',
            name='reply_type',
            field=models.CharField(choices=[('IP', 'In Progress'), ('IQ', 'In Progress - Response Required'), ('IC', 'In Progress - Response Received'), ('EC', 'Escalation'), ('CA', 'Closed - Assigned'), ('CR', 'Closed - Not Related'), ('CD', 'Closed - Not Responded'), ('CO', 'Closed - Resolved'), ('CL', 'Closed')], default='IP', max_length=2),
        ),
        migrations.AddField(
            model_name='enquiryticketreply',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AddField(
            model_name='enquiryticketreply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('RS', 'Resolved'), ('US', 'Unresolved'), ('IP', 'In Progress'), ('IQ', 'In Progress - Response Required'), ('IC', 'In Progress - Response Received'), ('EC', 'Escalation'), ('CA', 'Closed - Assigned'), ('CR', 'Closed - Not Related'), ('CD', 'Closed - Not Responded'), ('CO', 'Closed - Resolved'), ('CL', 'Closed')], default='IP', max_length=2),
        ),
    ]
