# Generated by Django 2.2.6 on 2020-11-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20201109_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryticketreply',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryticketreply',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
