# Generated by Django 2.2.6 on 2020-11-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20201110_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryticketreply',
            name='escalation_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
