# Generated by Django 2.2.6 on 2020-11-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_enquiryticketreply_escalation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryticketreply',
            name='reply_type',
            field=models.CharField(choices=[('IP', 'In Progress'), ('IQ', 'In Progress - Response Required'), ('IC', 'In Progress - Response Received'), ('AS', 'Assigned'), ('EC', 'Escalation'), ('CA', 'Closed - Assigned'), ('CR', 'Closed - Not Related'), ('CD', 'Closed - Not Responded'), ('CO', 'Closed - Resolved'), ('CL', 'Closed')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('RS', 'Resolved'), ('US', 'Unresolved'), ('AS', 'Assigned'), ('IP', 'In Progress'), ('IQ', 'In Progress - Response Required'), ('IC', 'In Progress - Response Received'), ('EC', 'Escalation'), ('CA', 'Closed - Assigned'), ('CR', 'Closed - Not Related'), ('CD', 'Closed - Not Responded'), ('CO', 'Closed - Resolved'), ('CL', 'Closed')], default='IP', max_length=2),
        ),
    ]
