# Generated by Django 2.2.6 on 2020-11-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20201110_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
